# Generated by Django 4.2.6 on 2023-10-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menuitem_menu_menu_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
