# Generated by Django 4.2.6 on 2023-10-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Названия меню')),
                ('items', models.ManyToManyField(to='menu.menuitem')),
            ],
        ),
    ]
