# Generated by Django 4.2.6 on 2023-10-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='link',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='link',
            field=models.CharField(max_length=512, null=True, verbose_name='Ссылка для перехода'),
        ),
    ]
